# Generated by Django 6.0.5 on 2026-05-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(max_length=50, unique=True, verbose_name='工号')),
                ('full_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], max_length=1, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('id_card', models.CharField(blank=True, max_length=18, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('leave_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', '在职'), ('inactive', '停用'), ('leave', '休假'), ('quit', '离职')], default='active', max_length=10)),
                ('department_id', models.BigIntegerField(blank=True, null=True)),
                ('department_name', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('work_shift_id', models.BigIntegerField(blank=True, null=True, verbose_name='班次ID')),
                ('skills', models.TextField(blank=True, help_text='JSON数组，如["焊工","叉车"]', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resignation_date', models.DateField(blank=True, null=True, verbose_name='离职日期')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'db_table': 'employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=100)),
                ('certificate_no', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('issuing_authority', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment_url', models.CharField(blank=True, max_length=255, null=True)),
                ('remind_before_days', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '员工证书',
                'verbose_name_plural': '员工证书',
                'db_table': 'employee_certificate',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('company_id', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '班次',
                'verbose_name_plural': '班次',
                'db_table': 'shift',
                'managed': True,
            },
        ),
    ]
