# Generated by Django 6.0.5 on 2026-05-20 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50, unique=True)),
                ('prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('date_format', models.CharField(blank=True, max_length=20, null=True)),
                ('seq_length', models.IntegerField(default=4)),
                ('current_seq', models.IntegerField(default=0)),
                ('company_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '编码规则',
                'verbose_name_plural': '编码规则',
                'db_table': 'code_rule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('company_id', models.BigIntegerField()),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '物料分类',
                'verbose_name_plural': '物料分类',
                'db_table': 'material_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('specification', models.CharField(blank=True, max_length=200, null=True)),
                ('unit', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='单价')),
                ('purchase_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('material_type', models.CharField(choices=[('raw', '原材料'), ('semi', '半成品'), ('finished', '成品'), ('auxiliary', '辅料')], default='raw', max_length=20)),
                ('safety_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_point', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('economic_order_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lead_time', models.IntegerField(default=0)),
                ('is_purchased', models.BooleanField(default=False)),
                ('is_produced', models.BooleanField(default=False)),
                ('cost_method', models.CharField(choices=[('weighted_avg', '月加权平均'), ('specific_id', '分批认定法'), ('standard', '标准成本法')], default='weighted_avg', max_length=20)),
                ('standard_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('last_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('company_id', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.materialcategory')),
            ],
            options={
                'verbose_name': '物料',
                'verbose_name_plural': '物料',
                'db_table': 'material',
                'managed': True,
            },
        ),
    ]
