# Generated by Django 5.2.14 on 2026-05-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialcategory',
            options={'managed': True, 'verbose_name': '物料分类', 'verbose_name_plural': '物料分类'},
        ),
    ]
