# Generated by Django 5.2.14 on 2026-06-10 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_alter_materialcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcategory',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='masterdata.materialcategory'),
        ),
    ]
