# Generated by Django 6.0.5 on 2026-05-20 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='公司名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='公司编码')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='登录账号')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('company_id', models.BigIntegerField(verbose_name='所属公司ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否员工')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user_system',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='部门编码')),
                ('manager', models.CharField(blank=True, max_length=50, verbose_name='负责人')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='system.company', verbose_name='所属公司')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'unique_together': {('name', 'company')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班组名称')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='班组编码')),
                ('leader', models.CharField(blank=True, max_length=50, verbose_name='班组长')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='system.company', verbose_name='所属公司')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '班组',
                'verbose_name_plural': '班组',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='工序名称')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='工序编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='system.team', verbose_name='所属班组')),
            ],
            options={
                'verbose_name': '工序',
                'verbose_name_plural': '工序',
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='车间名称')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='车间编码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='system.company', verbose_name='所属公司')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='system.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '车间',
                'verbose_name_plural': '车间',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='system.workshop', verbose_name='所属车间'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='岗位名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='岗位编码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='system.company', verbose_name='所属公司')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.department', verbose_name='所属部门')),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='权限组')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.process', verbose_name='所属工序')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.team', verbose_name='所属班组')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.workshop', verbose_name='所属车间')),
            ],
            options={
                'verbose_name': '岗位',
                'verbose_name_plural': '岗位',
            },
        ),
    ]
