# Generated by Django 5.2.14 on 2026-06-07 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_permission_role_rolepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='菜单编码')),
                ('path', models.CharField(blank=True, max_length=200, verbose_name='前端路由')),
                ('component', models.CharField(blank=True, max_length=200, verbose_name='前端组件')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='菜单图标')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序号')),
                ('permission_code', models.CharField(blank=True, max_length=100, verbose_name='权限编码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system.menu', verbose_name='上级菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RoleMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.menu', verbose_name='菜单')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色菜单',
                'verbose_name_plural': '角色菜单',
                'unique_together': {('role', 'menu')},
            },
        ),
    ]
