export const manufacturingModules = [
  {
    id: 'erp',
    name: '企业资源计划',
    shortName: 'ERP',
    englishName: 'Enterprise Resource Planning',
    position: '主数据、财务、应收应付与业财一体化基础平台',
    phase: '第一期 / 第二期',
    status: 'foundation',
    subModules: ['主数据管理', '应收管理', '应付管理', '业财一体', '数据字典', '编码规则', '工作中心配置', '参数配置', '多公司/多工厂/多部门资料权限'],
    coreData: ['物料', '客户', '供应商', '部门', '人员', '工作中心', '会计科目', '结算规则', '编码规则'],
    warningPoints: ['基础资料缺失预警', '应收逾期预警', '应付异常预警', '编码冲突预警'],
    integrationWith: ['ERP主数据 -> 全模块', 'SCM采购应付 -> ERP', 'CRM销售应收 -> ERP', 'WMS库存计价 -> ERP'],
  },
  {
    id: 'crm',
    name: '客户关系管理',
    shortName: 'CRM',
    englishName: 'Customer Relationship Management',
    position: '客户、销售、信用、订单交期预警',
    phase: '第二期',
    status: 'planning',
    subModules: ['客户档案', '客户价格策略', '客户物料对照', '报价单', '客户订单', '订单变更', '销货单', '销退单', '信用额度校验', '回款分析', '订单交期延误预警'],
    coreData: ['客户', '价格策略', '客户物料', '报价', '销售订单', '回款记录', '信用额度'],
    warningPoints: ['客户信用超限预警', '销售订单交期延误预警', '回款超期预警'],
    integrationWith: ['CRM订单/预测 -> MPS', 'CRM销货 -> WMS出库', 'CRM应收 -> ERP', 'MES进度 -> CRM交期预警'],
  },
  {
    id: 'scm',
    name: '供应链管理',
    shortName: 'SCM',
    englishName: 'Supply Chain Management',
    position: '采购、供应商、交期预警',
    phase: '第二期',
    status: 'planning',
    subModules: ['请购', '询价', '核价', '采购单', '进货', '退货', '对账', '供应商档案', '供应商价格', '供应商绩效', '催货清单'],
    coreData: ['供应商', '采购价格', '请购单', '采购单', '进货单', '退货单', '对账单', '交期记录'],
    warningPoints: ['供应商交期风险', '采购未到货预警', '供应商绩效异常'],
    integrationWith: ['MRP -> SCM请购建议', 'SCM进货 -> WMS采购入库', 'SCM应付 -> ERP', 'QMS来料质量 -> SCM供应商绩效'],
  },
  {
    id: 'wms',
    name: '仓储管理系统',
    shortName: 'WMS',
    englishName: 'Warehouse Management System',
    position: '多仓位、条码、库存预警',
    phase: '第二期',
    status: 'planning',
    subModules: ['多仓库', '多库位', '批号管理', '采购入库', '销售出库', '生产入库', '领料出库', '移库', '盘点', '安全库存', '库存预警', '条码/PDA扫码接口', '库龄分析', '呆滞料分析', '库存计价方式'],
    coreData: ['仓库', '库位', '批号', '库存余额', '出入库单据', '盘点单', '条码记录', '库存成本'],
    warningPoints: ['安全库存预警', '呆滞料预警', '库龄异常预警', '库存不足预警'],
    integrationWith: ['WMS库存 -> MRP', 'WMS领料 -> MES', 'WMS采购入库 -> SCM', 'WMS销售出库 -> CRM', 'WMS库存计价 -> ERP'],
  },
  {
    id: 'mrp',
    name: '物料需求计划',
    shortName: 'MRP',
    englishName: 'Material Requirements Planning',
    position: '净需求计算、采购与生产建议',
    phase: '第三期',
    status: 'planning',
    subModules: ['BOM读取', '库存读取', 'MPS读取', '净需求计算', '替代料处理', '损耗率处理', '采购请购建议', '制造工单建议', '来料交期延误预警', '催货函生成', 'MRP重算建议'],
    coreData: ['BOM', 'MPS', '库存', '已分配量', '已订购量', '净需求', '请购建议', '工单建议'],
    warningPoints: ['缺料预警', '来料延误预警', 'MRP重算建议'],
    integrationWith: ['MPS -> MRP', 'ERP/BOM/WMS库存 -> MRP', 'MRP -> SCM请购', 'MRP -> MES工单建议'],
  },
  {
    id: 'mps',
    name: '主生产计划',
    shortName: 'MPS',
    englishName: 'Master Production Schedule',
    position: '成品计划与粗能力校验，是 MRP 的上游输入',
    phase: '第四期',
    status: 'planning',
    subModules: ['客户订单汇总', '销售预测', '按产品/日/周/月编制MPS', '粗能力校验', '产能超限提示', 'MPS审核', 'MPS锁定', 'MPS修改', 'MPS重排', '作为MRP运算唯一输入'],
    coreData: ['销售订单', '销售预测', '成品计划', '粗能力负荷', '审核状态', '锁定状态'],
    warningPoints: ['粗能力超限预警', '计划冲突预警'],
    integrationWith: ['CRM订单/预测 -> MPS', '审核后MPS -> MRP', 'MPS计划约束 -> APS'],
  },
  {
    id: 'aps',
    name: '高级计划排程',
    shortName: 'APS',
    englishName: 'Advanced Planning and Scheduling',
    position: '有限产能排程与甘特图',
    phase: '第四期',
    status: 'planning',
    subModules: ['物料约束', '产能约束', '工艺路线约束', '工序级任务分解', '设备/工作中心分配', '自动排程', '插单重排', '甘特图展示', '拖拽调整预留', '预计开工/完工时间输出', '派工单生成'],
    coreData: ['工艺路线', '工序任务', '设备能力', '工作中心日历', '排程结果', '派工单'],
    warningPoints: ['产能冲突预警', '插单影响预警', '排程延误预警'],
    integrationWith: ['MPS/MRP约束 -> APS', 'APS排程 -> MES派工', 'MES进度 -> APS重排'],
  },
  {
    id: 'mes',
    name: '制造执行系统',
    shortName: 'MES',
    englishName: 'Manufacturing Execution System',
    position: '工单执行、报工、进度预警',
    phase: '第四期',
    status: 'planning',
    subModules: ['工单管理', '厂内工单', '委外工单', '领料', '退料', '生产入库', '车间任务', '工艺路线', 'PDA扫码开工', '工序转移', '报工', '完工入库', '工时采集', '设备数据采集接口', '班次管理', '生产进度延误预警', '与APS联动重排'],
    coreData: ['工单', '派工单', '领料单', '工序', '报工记录', '工时', '设备采集数据', '班次'],
    warningPoints: ['工单进度延误预警', '工序延误预警', '设备故障预警', '人员不足预警'],
    integrationWith: ['MRP工单建议 -> MES', 'APS派工 -> MES', 'MES进度 -> CRM/APS/BI/KPI/FDM', 'MES完工 -> WMS生产入库'],
  },
  {
    id: 'qms',
    name: '质量管理系统',
    shortName: 'QMS',
    englishName: 'Quality Management System',
    position: '检验、不合格处理、品质预警',
    phase: '第五期',
    status: 'planning',
    subModules: ['检验标准', '检验模板', '来料检验', '制程检验', '出货检验', '检验记录', '自动判定合格/不合格', '不合格处理流程', '退货', '返工', '让步接收', '报废', '条码追溯', '品质异常预警', '8D报告预留'],
    coreData: ['检验标准', '检验模板', '检验记录', '不合格单', '返工记录', '追溯码', '8D报告'],
    warningPoints: ['来料不合格预警', '制程异常预警', '连续不良预警', '不良率超限预警'],
    integrationWith: ['QMS来料质量 -> SCM', 'QMS制程质量 -> MES', 'QMS库存状态 -> WMS', 'QMS质量指标 -> KPI'],
  },
  {
    id: 'bi',
    name: '商业智能',
    shortName: 'BI',
    englishName: 'Business Intelligence',
    position: '报表、驾驶舱、自定义分析',
    phase: '第六期',
    status: 'planning',
    subModules: ['供应商评估', '库存优化', '财务分析', '生产效能', '销售分析', '自定义报表', '图表展示', 'Excel/PDF导出预留', '定时发送预留', '预警推送'],
    coreData: ['报表模型', '指标口径', '图表配置', '导出任务', '订阅任务', '预警推送规则'],
    warningPoints: ['关键指标阈值预警', '报表数据异常提示'],
    integrationWith: ['ERP/CRM/SCM/WMS/MES/QMS -> BI', 'BI分析 -> 管理驾驶舱', 'BI指标 -> KPI/FDM'],
  },
  {
    id: 'fdm',
    name: '生产数据可视化大屏',
    shortName: 'FDM',
    englishName: 'Factory Data Monitor',
    position: '车间实时看板',
    phase: '第六期',
    status: 'planning',
    subModules: ['生产进度看板', '质量看板', '设备看板', '库存看板', '人员看板', 'WebSocket自动刷新预留', '车间实时状态展示'],
    coreData: ['车间状态', '生产进度', '质量状态', '设备状态', '人员状态', '库存状态', '刷新通道'],
    warningPoints: ['关键指标阈值预警', '看板异常状态提示'],
    integrationWith: ['MES实时进度 -> FDM', 'QMS质量 -> FDM', 'WMS库存 -> FDM', 'PFM人员 -> FDM', 'BI/KPI指标 -> FDM'],
  },
  {
    id: 'pfm',
    name: '人员档案维护',
    shortName: 'PFM',
    englishName: 'Personnel File Management',
    position: '员工信息、技能、班次管理',
    phase: '第一期',
    status: 'foundation',
    subModules: ['人员基本信息', '工号', '部门', '岗位', '合同信息', '联系方式', '附件上传预留', '技能标签', '证书管理', '证书到期提醒', '培训记录', '排班', '考勤接口预留', '人员状态', '账号权限关联'],
    coreData: ['人员档案', '工号', '部门岗位', '合同', '技能标签', '证书', '培训记录', '排班', '账号权限'],
    warningPoints: ['证书到期预警', '人员状态异常预警', '班次缺员预警'],
    integrationWith: ['PFM人员 -> ERP主数据', 'PFM技能/班次 -> MES/APS', 'PFM人员状态 -> KPI/FDM'],
  },
  {
    id: 'kpi',
    name: '绩效管理',
    shortName: 'KPI',
    englishName: 'Key Performance Indicator Management',
    position: '指标自动计算与考核',
    phase: '第六期',
    status: 'planning',
    subModules: ['KPI指标库', '产量达成率', '一次合格率', '工时效率', '设备稼动率', '按时交付率', '采购交期准时率', '库存周转率', '应收账款周转率', '数据自动抓取', '个人/班组/部门/工厂考核', '日/周/月/季/年考核周期', '绩效看板', '绩效报表导出预留', '绩效改进分析'],
    coreData: ['指标库', '考核对象', '考核周期', '指标采集值', '评分规则', '绩效报表'],
    warningPoints: ['指标未达成预警', '部门绩效异常预警'],
    integrationWith: ['ERP/CRM/SCM/WMS/MES/QMS -> KPI', 'KPI结果 -> BI/FDM', 'KPI改进 -> 管理闭环'],
  },
]

export function getManufacturingModules() {
  return manufacturingModules
}

export function getManufacturingModuleById(moduleId) {
  return manufacturingModules.find((module) => module.id === moduleId)
}

export function getManufacturingModuleSummary() {
  return {
    total: manufacturingModules.length,
    status: {
      foundation: manufacturingModules.filter((module) => module.status === 'foundation').length,
      planning: manufacturingModules.filter((module) => module.status === 'planning').length,
      developing: manufacturingModules.filter((module) => module.status === 'developing').length,
      ready: manufacturingModules.filter((module) => module.status === 'ready').length,
    },
  }
}
