from system.models import Menu, Role, RoleMenu

menus = [
    {
        "name": "仪表盘",
        "code": "dashboard",
        "path": "/dashboard",
        "component": "views/Dashboard.vue",
        "icon": "DataBoard",
        "sort_order": 1,
        "permission_code": "dashboard_view",
        "children": [
            {
                "name": "工作台",
                "code": "dashboard_workbench",
                "path": "/dashboard/workbench",
                "component": "views/Dashboard.vue",
                "icon": "Monitor",
                "sort_order": 101,
                "permission_code": "dashboard_view",
            },
            {
                "name": "经营看板",
                "code": "dashboard_business",
                "path": "/dashboard/business",
                "component": "views/Dashboard.vue",
                "icon": "DataAnalysis",
                "sort_order": 102,
                "permission_code": "dashboard_view",
            },
            {
                "name": "预警中心",
                "code": "dashboard_warning",
                "path": "/dashboard/warning",
                "component": "views/Dashboard.vue",
                "icon": "Bell",
                "sort_order": 103,
                "permission_code": "dashboard_view",
            },
        ],
    },
    {
        "name": "主数据",
        "code": "masterdata",
        "path": "/masterdata",
        "component": "",
        "icon": "Collection",
        "sort_order": 2,
        "permission_code": "masterdata_view",
        "children": [
            {
                "name": "物料分类",
                "code": "masterdata_material_category",
                "path": "/masterdata/material-category",
                "component": "views/MaterialCategoryList.vue",
                "icon": "Files",
                "sort_order": 201,
                "permission_code": "material_category_view",
            },
            {
                "name": "物料档案",
                "code": "masterdata_material",
                "path": "/masterdata/material",
                "component": "views/MaterialList.vue",
                "icon": "Box",
                "sort_order": 202,
                "permission_code": "material_view",
            },
            {
                "name": "供应商档案",
                "code": "masterdata_supplier",
                "path": "/masterdata/supplier",
                "component": "views/SupplierList.vue",
                "icon": "OfficeBuilding",
                "sort_order": 203,
                "permission_code": "supplier_view",
            },
            {
                "name": "客户档案",
                "code": "masterdata_customer",
                "path": "/masterdata/customer",
                "component": "views/ComingSoon.vue",
                "icon": "User",
                "sort_order": 204,
                "permission_code": "customer_view",
            },
        ],
    },
    {
        "name": "采购管理",
        "code": "purchase",
        "path": "/purchase",
        "component": "",
        "icon": "ShoppingCart",
        "sort_order": 3,
        "permission_code": "purchase_view",
        "children": [
            {
                "name": "采购申请",
                "code": "purchase_request",
                "path": "/purchase/request",
                "component": "views/ComingSoon.vue",
                "icon": "DocumentAdd",
                "sort_order": 301,
                "permission_code": "purchase_request_view",
            },
            {
                "name": "采购订单",
                "code": "purchase_order",
                "path": "/purchase/order",
                "component": "views/PurchaseOrderList.vue",
                "icon": "Document",
                "sort_order": 302,
                "permission_code": "purchase_order_view",
            },
            {
                "name": "到货登记",
                "code": "purchase_arrival",
                "path": "/purchase/arrival",
                "component": "views/ComingSoon.vue",
                "icon": "TakeawayBox",
                "sort_order": 303,
                "permission_code": "purchase_arrival_view",
            },
            {
                "name": "采购统计",
                "code": "purchase_report",
                "path": "/purchase/report",
                "component": "views/PurchaseReports.vue",
                "icon": "PieChart",
                "sort_order": 304,
                "permission_code": "purchase_report_view",
            },
        ],
    },
    {
        "name": "员工中心",
        "code": "hr",
        "path": "/hr",
        "component": "",
        "icon": "UserFilled",
        "sort_order": 4,
        "permission_code": "hr_view",
        "children": [
            {
                "name": "员工管理",
                "code": "hr_employee",
                "path": "/hr/employee",
                "component": "views/EmployeeList.vue",
                "icon": "User",
                "sort_order": 401,
                "permission_code": "employee_view",
            },
            {
                "name": "证书管理",
                "code": "hr_certificate",
                "path": "/hr/certificate",
                "component": "views/CertificateList.vue",
                "icon": "Tickets",
                "sort_order": 402,
                "permission_code": "certificate_view",
            },
            {
                "name": "培训管理",
                "code": "hr_training",
                "path": "/hr/training",
                "component": "views/ComingSoon.vue",
                "icon": "Reading",
                "sort_order": 403,
                "permission_code": "training_view",
            },
            {
                "name": "考勤管理",
                "code": "hr_attendance",
                "path": "/hr/attendance",
                "component": "views/ComingSoon.vue",
                "icon": "Clock",
                "sort_order": 404,
                "permission_code": "attendance_view",
            },
        ],
    },
    {
        "name": "效益管理",
        "code": "profit",
        "path": "/profit",
        "component": "",
        "icon": "TrendCharts",
        "sort_order": 5,
        "permission_code": "profit_view",
        "children": [
            {
                "name": "实时效益",
                "code": "profit_realtime",
                "path": "/profit/realtime",
                "component": "views/ComingSoon.vue",
                "icon": "DataLine",
                "sort_order": 501,
                "permission_code": "profit_realtime_view",
            },
            {
                "name": "成本分析",
                "code": "profit_cost",
                "path": "/profit/cost",
                "component": "views/ComingSoon.vue",
                "icon": "Money",
                "sort_order": 502,
                "permission_code": "profit_cost_view",
            },
            {
                "name": "利润分析",
                "code": "profit_analysis",
                "path": "/profit/analysis",
                "component": "views/ComingSoon.vue",
                "icon": "Histogram",
                "sort_order": 503,
                "permission_code": "profit_analysis_view",
            },
            {
                "name": "改善项目",
                "code": "profit_improvement",
                "path": "/profit/improvement",
                "component": "views/ComingSoon.vue",
                "icon": "Opportunity",
                "sort_order": 504,
                "permission_code": "profit_improvement_view",
            },
            {
                "name": "效益排行榜",
                "code": "profit_ranking",
                "path": "/profit/ranking",
                "component": "views/ComingSoon.vue",
                "icon": "Rank",
                "sort_order": 505,
                "permission_code": "profit_ranking_view",
            },
        ],
    },
    {
        "name": "系统管理",
        "code": "system",
        "path": "/system",
        "component": "",
        "icon": "Setting",
        "sort_order": 6,
        "permission_code": "system_view",
        "children": [
            {
                "name": "组织架构",
                "code": "system_org",
                "path": "/system/org",
                "component": "views/ComingSoon.vue",
                "icon": "OfficeBuilding",
                "sort_order": 601,
                "permission_code": "system_org_view",
            },
            {
                "name": "部门管理",
                "code": "system_department",
                "path": "/system/department",
                "component": "views/ComingSoon.vue",
                "icon": "Connection",
                "sort_order": 602,
                "permission_code": "system_department_view",
            },
            {
                "name": "岗位管理",
                "code": "system_position",
                "path": "/system/position",
                "component": "views/ComingSoon.vue",
                "icon": "Suitcase",
                "sort_order": 603,
                "permission_code": "system_position_view",
            },
            {
                "name": "用户管理",
                "code": "system_user",
                "path": "/system/user",
                "component": "views/ComingSoon.vue",
                "icon": "Avatar",
                "sort_order": 604,
                "permission_code": "system_user_view",
            },
            {
                "name": "角色管理",
                "code": "system_role",
                "path": "/system/role",
                "component": "views/ComingSoon.vue",
                "icon": "Key",
                "sort_order": 605,
                "permission_code": "system_role_view",
            },
            {
                "name": "权限管理",
                "code": "system_permission",
                "path": "/system/permission",
                "component": "views/ComingSoon.vue",
                "icon": "Lock",
                "sort_order": 606,
                "permission_code": "system_permission_view",
            },
            {
                "name": "菜单管理",
                "code": "system_menu",
                "path": "/system/menu",
                "component": "views/ComingSoon.vue",
                "icon": "Menu",
                "sort_order": 607,
                "permission_code": "system_menu_view",
            },
            {
                "name": "系统日志",
                "code": "system_log",
                "path": "/system/log",
                "component": "views/ComingSoon.vue",
                "icon": "Document",
                "sort_order": 608,
                "permission_code": "system_log_view",
            },
        ],
    },
]


def create_menu(item, parent=None):
    menu, _ = Menu.objects.update_or_create(
        code=item["code"],
        defaults={
            "name": item["name"],
            "path": item["path"],
            "component": item["component"],
            "icon": item["icon"],
            "parent": parent,
            "sort_order": item["sort_order"],
            "permission_code": item["permission_code"],
            "is_active": True,
        },
    )

    for child in item.get("children", []):
        create_menu(child, parent=menu)

    return menu


for item in menus:
    create_menu(item)


try:
    super_role = Role.objects.get(code="superadmin")
    for menu in Menu.objects.all():
        RoleMenu.objects.get_or_create(role=super_role, menu=menu)
    print("菜单初始化完成，并已分配给超级管理员")
except Role.DoesNotExist:
    print("未找到超级管理员角色，请先执行 system/init_permissions.py")
