# Generated by Django 6.0.5 on 2026-05-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('customer', models.CharField(max_length=100, verbose_name='客户')),
                ('contact', models.CharField(max_length=50, verbose_name='联系人')),
                ('createDate', models.DateField(verbose_name='创建日期')),
                ('dueDate', models.DateField(verbose_name='截止日期')),
                ('completeDate', models.DateField(blank=True, null=True, verbose_name='完成日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
            ],
            options={
                'db_table': 'purchase_orders',
                'ordering': ['-createDate'],
            },
        ),
    ]
