# Generated by Django 5.2.14 on 2026-06-09 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-order_date', '-id'], 'verbose_name': '采购订单', 'verbose_name_plural': '采购订单'},
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='completeDate',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='createDate',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='dueDate',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='orderNo',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='status',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='actual_receive_date',
            field=models.DateField(blank=True, null=True, verbose_name='实际到货日期'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='采购员'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='document_status',
            field=models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('audited', '已审核'), ('reviewed', '已复核'), ('approved', '已审批'), ('rejected', '已驳回'), ('cancelled', '已作废'), ('closed', '已关闭'), ('finished', '已结案')], default='draft', max_length=30, verbose_name='单据状态'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='expected_date',
            field=models.DateField(blank=True, null=True, verbose_name='预计到货日期'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_on_time_delivery',
            field=models.BooleanField(default=False, verbose_name='是否准交达成'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='下单日期'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='po_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='采购订单号'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='progress_status',
            field=models.CharField(choices=[('not_started', '未开始'), ('arriving', '到货中'), ('arrived', '已到货'), ('inspecting', '检验中'), ('inspected', '已检验'), ('warehousing', '入库中'), ('warehoused', '已入库'), ('settling', '结算中'), ('settled', '已结算'), ('finished', '已结案')], default='not_started', max_length=30, verbose_name='执行进度'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_department',
            field=models.CharField(blank=True, max_length=100, verbose_name='物料申购部门'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='remark',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='require_department',
            field=models.CharField(blank=True, max_length=100, verbose_name='物料需求部门'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='供应商名称'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_actual_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='实际总金额'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_plan_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='计划总金额'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='urgency_level',
            field=models.CharField(choices=[('very_urgent', '特急'), ('urgent', '紧急'), ('normal', '一般'), ('loose', '宽松'), ('completed', '已完成'), ('no_plan', '未计划')], default='normal', max_length=30, verbose_name='紧急程度'),
        ),
        migrations.CreateModel(
            name='PurchaseApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_level', models.CharField(choices=[('audit', '审核'), ('review', '复核'), ('approve', '审批')], max_length=30, verbose_name='审批级别')),
                ('approver_name', models.CharField(blank=True, max_length=50, verbose_name='审批人')),
                ('approval_result', models.CharField(choices=[('pending', '待处理'), ('passed', '通过'), ('rejected', '驳回')], default='pending', max_length=30, verbose_name='审批结果')),
                ('approval_comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='purchase.purchaseorder', verbose_name='采购订单')),
            ],
            options={
                'verbose_name': '采购审批记录',
                'verbose_name_plural': '采购审批记录',
                'db_table': 'purchase_approval_records',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=50, verbose_name='物料编码')),
                ('material_name', models.CharField(max_length=100, verbose_name='物料名称')),
                ('specification', models.CharField(blank=True, max_length=100, verbose_name='规格型号')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='单位')),
                ('plan_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='计划数量')),
                ('actual_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='实际数量')),
                ('plan_unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='计划单价')),
                ('actual_unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='实际单价')),
                ('plan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='计划金额')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='实际金额')),
                ('plan_delivery_date', models.DateField(blank=True, null=True, verbose_name='计划交期')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='实际交期')),
                ('arrival_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='到货数量')),
                ('qualified_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='合格数量')),
                ('rejected_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='不合格数量')),
                ('inbound_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='入库数量')),
                ('settled_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='已结算数量')),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='已结算金额')),
                ('is_on_time_delivery', models.BooleanField(default=False, verbose_name='是否准交达成')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchaseorder', verbose_name='采购订单')),
            ],
            options={
                'verbose_name': '采购订单明细',
                'verbose_name_plural': '采购订单明细',
                'db_table': 'purchase_order_items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseExecutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('arrival', '到货'), ('inspect', '检验'), ('inbound', '入库'), ('settle', '结算'), ('finish', '结案'), ('close', '关闭'), ('cancel', '作废'), ('restart', '重启')], max_length=30, verbose_name='执行动作')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='数量')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='金额')),
                ('operator_name', models.CharField(blank=True, max_length=50, verbose_name='操作人')),
                ('action_date', models.DateField(blank=True, null=True, verbose_name='执行日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_records', to='purchase.purchaseorder', verbose_name='采购订单')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_records', to='purchase.purchaseorderitem', verbose_name='采购订单明细')),
            ],
            options={
                'verbose_name': '采购执行记录',
                'verbose_name_plural': '采购执行记录',
                'db_table': 'purchase_execution_records',
            },
        ),
    ]
