# Generated by Django 6.0.5 on 2026-05-20 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('order_date', models.DateField()),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('actual_receive_date', models.DateField(blank=True, null=True, verbose_name='实际到货日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已审核'), ('reviewed', '已复核'), ('final_approved', '已审批'), ('received', '已收货'), ('inspected', '已检验'), ('stored', '已入库'), ('closed', '已结案'), ('cancelled', '已取消')], default='draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remark', models.TextField(blank=True, null=True)),
                ('buyer', models.CharField(blank=True, max_length=50, null=True, verbose_name='采购员')),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('company_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '采购订单',
                'verbose_name_plural': '采购订单',
                'db_table': 'purchase_order',
                'ordering': ['-id'],
                'permissions': [('can_submit_purchaseorder', '可以提交订单'), ('can_approve_purchaseorder', '可以审核订单'), ('can_review_purchaseorder', '可以复核订单'), ('can_final_approve_purchaseorder', '可以审批订单'), ('can_receive_purchaseorder', '可以收货'), ('can_inspect_purchaseorder', '可以检验'), ('can_store_purchaseorder', '可以入库'), ('can_close_purchaseorder', '可以结案'), ('can_cancel_purchaseorder', '可以取消订单'), ('can_restart_purchaseorder', '可以重启订单')],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('credit_rating', models.CharField(choices=[('A', 'A级'), ('B', 'B级'), ('C', 'C级'), ('D', 'D级')], default='B', max_length=1)),
                ('payment_terms', models.CharField(blank=True, max_length=50, null=True)),
                ('lead_time', models.IntegerField(default=0)),
                ('company_id', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'db_table': 'supplier',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='商品名称')),
                ('specification', models.CharField(blank=True, max_length=200, null=True, verbose_name='规格型号')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='计划数量')),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='计划单价')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='计划金额')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='实际交货数量')),
                ('actual_unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='实际交货单价')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='实际交货金额')),
                ('actual_arrival_date', models.DateField(blank=True, null=True, verbose_name='实际到货日期')),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.material', verbose_name='物料')),
                ('po', models.ForeignKey(db_column='po_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaseorder')),
            ],
            options={
                'verbose_name': '采购订单明细',
                'verbose_name_plural': '采购订单明细',
                'db_table': 'purchase_order_item',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(db_column='supplier_id', on_delete=django.db.models.deletion.CASCADE, to='procurement.supplier'),
        ),
    ]
