# Generated by Django 5.2.14 on 2026-06-01 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_purchaseorder_department'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='require_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='require_orders', to='system.department', verbose_name='物料需求部门'),
        ),
    ]
