# Generated by Django 5.2.14 on 2026-06-03 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_purchaseorder_require_department'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='system.department', verbose_name='物料申购部门'),
        ),
    ]
